spring:
  application:
    name: 'auth-service'

  profiles:
    active: 'local'

  liquibase:
    enabled: 'true'
    change-log: 'classpath:/db/changelog/db.changelog-master.yml'
    default-schema: 'app'

server:
  port: '9000'
