spring:
  application:
    name: 'auth-service'

  profiles:
    active: "${APPLICATION_PROFILE}"

  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: 'validate'
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: 'app'

  liquibase:
    enabled: 'true'
    change-log: 'classpath:/db/changelog/db.changelog-master.yml'
    default-schema: 'app'

application:
  security:
    enabled: 'true'
    secretKey: "${TOKEN_SECRET}"
    issuer: 'InnowiseGroup'
    ttl:
      access: '15m'
      refresh: '15d'